#!/bin/bash

##########################
# Variables
##########################

PIDFILE=/var/run/awsbackupS3list.pid

##########################
# Functions
##########################

cleanexit() {
  rm $PIDFILE
  exit 0
}

stop_script () {
  rm $PIDFILE
  exit 70
}

if [ -f $PIDFILE ]
then
  PID=$(cat $PIDFILE)
  ps -p $PID > /dev/null 2>&1
  if [ $? -eq 0 ]
  then
    echo "Process already running"
    exit 1
  else
    ## Process not found assume not running
    echo $$ > $PIDFILE
    if [ $? -ne 0 ]
    then
      echo "Could not create PID file"
      exit 1
    fi
  fi
else
  echo $$ > $PIDFILE
  if [ $? -ne 0 ]
  then
    echo "Could not create PID file"
    exit 1
  fi
fi

aws s3 ls s3://backups-container/ | tr -s " " > /var/lib/zabbix/awsbackup.list

rm $PIDFILE

trap SIGINT

exit 0